### ISSUE TITLE
Errors while using ng-popover basic example

### ISSUE THREAD

**Issue by danaERadwin** [pleerock/ng2-popover#47]
I am using Angular 2 version 1.0.0-beta.18.
I installed ng2-popover package and get the following error after I  have imported the PopoverModule in the @ngModule (the actual code is in comment):

```
ctorParameters.map is not a function
    at ReflectionCapabilities.parameters (http://localhost:4200/main.bundle.js:40097:45)
    at Reflector.parameters (http://localhost:4200/main.bundle.js:40231:44)
    at CompileMetadataResolver.getDependenciesMetadata (http://localhost:4200/main.bundle.js:21949:54)
    at CompileMetadataResolver.getTypeMetadata (http://localhost:4200/main.bundle.js:21914:26)
    at CompileMetadataResolver.getDirectiveMetadata (http://localhost:4200/main.bundle.js:21689:28)
    at http://localhost:4200/main.bundle.js:21758:49
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:4200/main.bundle.js:21751:44)
    at http://localhost:4200/main.bundle.js:21739:50
    at Array.forEach (native)

```

Please advice

**Comment by VishalGulati** [comment]
also facing the same issue. 
Error: (SystemJS) ctorParameters.map is not a function.

Could anyone tell what could be causing this. here is my package json:
```

{
  "name": "angular-quickstart",
  "version": "1.0.0",
  "description": "QuickStart package.json from the documentation, supplemented with testing support",
  "scripts": {
    "start": "concurrently \"npm run tsc:w\" \"npm run lite\" ",
    "e2e": "tsc && concurrently \"http-server -s\" \"protractor protractor.config.js\" --kill-others --success first",
    "lint": "tslint ./app/**/*.ts -t verbose",
    "lite": "lite-server",
    "pree2e": "webdriver-manager update",
    "test": "tsc && concurrently \"tsc -w\" \"karma start karma.conf.js\"",
    "test-once": "tsc && karma start karma.conf.js --single-run",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "clean": "rm -rf dist",
    "serve": "http-server . -p 5556",
    "build": "npm run clean && tsc",
    "build_prod": "npm run build && browserify -s main dist/main.js > dist/bundle.js && npm run minify",
    "minify": "uglifyjs dist/main-content-main.js --screw-ie8 --compress --mangle --output dist/bundle.min.js"
  },
  "keywords": [],
  "author": "",
  "license": "MIT",
  "dependencies": {
    "@angular/common": "2.1.2",
    "@angular/compiler": "2.1.2",
    "@angular/compiler-cli": "2.1.2",
    "@angular/core": "2.1.2",
    "@angular/forms": "2.1.2",
    "@angular/http": "2.1.2",
    "@angular/platform-browser": "2.1.2",
    "@angular/platform-browser-dynamic": "2.1.2",
    "@angular/platform-server": "2.2.1",
    "@angular/router": "3.2.1",
    "angular-in-memory-web-api": "0.2.3",
    "core-js": "^2.4.1",
    "moment": "^2.17.1",
    "ng2-bootstrap": "1.1.14",
    "ng2-facebook-sdk": "^1.0.0",
    "ng2-popover": "0.0.13",
    "reflect-metadata": "^0.1.8",
    "rollup-plugin-multi-entry": "^2.0.1",
    "rxjs": "5.0.0-beta.12",
    "systemjs": "0.19.40",
    "zone.js": "^0.7.2"
  },
  "devDependencies": {
    "@types/jasmine": "^2.5.36",
    "@types/node": "^6.0.46",
    "@types/selenium-webdriver": "^2.53.33",
    "canonical-path": "0.0.2",
    "concurrently": "^3.1.0",
    "http-server": "^0.9.0",
    "jasmine-core": "~2.4.1",
    "karma": "^1.3.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "lite-server": "^2.2.2",
    "lodash": "^4.16.4",
    "protractor": "4.0.9",
    "rimraf": "^2.5.4",
    "rollup": "^0.36.4",
    "rollup-plugin-commonjs": "^5.0.5",
    "rollup-plugin-node-resolve": "^2.0.0",
    "rollup-plugin-uglify": "^1.0.1",
    "tslint": "^3.15.1",
    "typescript": "~2.0.10",
    "webdriver-manager": "10.2.5"
  },
  "repository": {}
}

```

**Comment by Nikolay-Uvarov** [comment]
I have the same problem now, but i used this package 2 month ago and had not any problem.
